const femto = @import("femto.zig");

export fn no_return_handler() callconv(.C) void {
    while (true) {}
}

export fn null_handler() callconv(.C) void {}

export fn _start() callconv(.C) void {
    femto.begin();
    while (true) {}
}

const handler_fn = ?fn () callconv(.C) void;

const _stack: u32 = 0x20000000 + (20 * 1024);

pub const vectors_connectivity = packed struct {
    stack: u32,
    reset: handler_fn,
    nmi: handler_fn,
    hardfault: handler_fn,
    memManage: handler_fn,
    busFault: handler_fn,
    usageFault: handler_fn,
    res: [4]u32 = [_]u32{ 0, 0, 0, 0 },
    svCall: handler_fn,
    debugMonitor: handler_fn,
    res2: u32 = 0,
    pensv: handler_fn,
    systick: handler_fn,
    wwdg: handler_fn,
    pvd: handler_fn,
    tamper: handler_fn,
    rtc: handler_fn,
    flash: handler_fn,
    rcc: handler_fn,
    exti0: handler_fn,
    exti1: handler_fn,
    exti2: handler_fn,
    exti3: handler_fn,
    exti4: handler_fn,
    dma1_1: handler_fn,
    dma1_2: handler_fn,
    dma1_3: handler_fn,
    dma1_4: handler_fn,
    dma1_5: handler_fn,
    dma1_6: handler_fn,
    dma1_7: handler_fn,
    adc1_2: handler_fn,
    can1_tx: handler_fn,
    can2_rx0: handler_fn,
    can1_rx1: handler_fn,
    can1_sce: handler_fn,
    exti9_5: handler_fn,
    tim1_brk: handler_fn,
    tim1_up: handler_fn,
    tim1_trg_con: handler_fn,
    tim1_cc: handler_fn,
    tim2: handler_fn,
    tim3: handler_fn,
    tim4: handler_fn,
    i2c1_ev: handler_fn,
    i2c1_er: handler_fn,
    i2c2_ev: handler_fn,
    i2c2_er: handler_fn,
    sp11: handler_fn,
    spi2: handler_fn,
    usart1: handler_fn,
    usart2: handler_fn,
    usart3: handler_fn,
    exti15_10: handler_fn,
    rtcalarm: handler_fn,
    otg_fs_wkup: handler_fn,
    res3: [6]u32 = [_]u32{ 0, 0, 0, 0, 0, 0 },
    tim5: handler_fn,
    spi3: handler_fn,
    uart4: handler_fn,
    uart5: handler_fn,
    tim6: handler_fn,
    tim7: handler_fn,
    dma2_1: handler_fn,
    dma2_2: handler_fn,
    dma2_3: handler_fn,
    dma2_4: handler_fn,
    dma2_5: handler_fn,
    eth: handler_fn,
    eth_wkup: handler_fn,
    can2_tx: handler_fn,
    can2_rx0: handler_fn,
    can2_rx1: handler_fn,
    can2_sce: handler_fn,
    otg_fs: handler_fn,
};

pub const vectors_xl = packed struct {
    stack: u32,
    reset: handler_fn,
    nmi: handler_fn,
    hardfault: handler_fn,
    memManage: handler_fn,
    busFault: handler_fn,
    usageFault: handler_fn,
    res: [4]u32 = [_]u32{ 0, 0, 0, 0 },
    svCall: handler_fn,
    debugMonitor: handler_fn,
    res2: u32 = 0,
    pensv: handler_fn,
    systick: handler_fn,
    wwdg: handler_fn,
    pvd: handler_fn,
    tamper: handler_fn,
    rtc: handler_fn,
    flash: handler_fn,
    rcc: handler_fn,
    exti0: handler_fn,
    exti1: handler_fn,
    exti2: handler_fn,
    exti3: handler_fn,
    exti4: handler_fn,
    dma1_1: handler_fn,
    dma1_2: handler_fn,
    dma1_3: handler_fn,
    dma1_4: handler_fn,
    dma1_5: handler_fn,
    dma1_6: handler_fn,
    dma1_7: handler_fn,
    adc1_2: handler_fn,
    usb_hp_can_tx: handler_fn,
    usb_lp_can_rx0: handler_fn,
    can1_rx1: handler_fn,
    can1_sce: handler_fn,
    exti9_5: handler_fn,
    tim1_brk_tim9: handler_fn,
    tim1_up_tim10: handler_fn,
    tim1_trg_con_tim11: handler_fn,
    tim1_cc: handler_fn,
    tim2: handler_fn,
    tim3: handler_fn,
    tim4: handler_fn,
    i2c1_ev: handler_fn,
    i2c1_er: handler_fn,
    i2c2_ev: handler_fn,
    i2c2_er: handler_fn,
    sp11: handler_fn,
    spi2: handler_fn,
    usart1: handler_fn,
    usart2: handler_fn,
    usart3: handler_fn,
    exti15_10: handler_fn,
    rtcalarm: handler_fn,
    usb_wkup: handler_fn,
    tim8_brk_tim12: handler_fn,
    tim8_up_tim13: handler_fn,
    tim8_trg_com_tim14: handler_fn,
    tim8_cc: handler_fn,
    adc3: handler_fn,
    fsmc: handler_fn,
    sdio: handler_fn,
    tim5: handler_fn,
    spi3: handler_fn,
    uart4: handler_fn,
    uart5: handler_fn,
    tim6: handler_fn,
    tim7: handler_fn,
    dma2_1: handler_fn,
    dma2_2: handler_fn,
    dma2_3: handler_fn,
    dma2_4_5: handler_fn,
};

pub const vectors_other = packed struct {
    stack: u32,
    reset: handler_fn,
    nmi: handler_fn,
    hardfault: handler_fn,
    memManage: handler_fn,
    busFault: handler_fn,
    usageFault: handler_fn,
    res: [4]u32 = [_]u32{ 0, 0, 0, 0 },
    svCall: handler_fn,
    debugMonitor: handler_fn,
    res2: u32 = 0,
    pensv: handler_fn,
    systick: handler_fn,
    wwdg: handler_fn,
    pvd: handler_fn,
    tamper: handler_fn,
    rtc: handler_fn,
    flash: handler_fn,
    rcc: handler_fn,
    exti0: handler_fn,
    exti1: handler_fn,
    exti2: handler_fn,
    exti3: handler_fn,
    exti4: handler_fn,
    dma1_1: handler_fn,
    dma1_2: handler_fn,
    dma1_3: handler_fn,
    dma1_4: handler_fn,
    dma1_5: handler_fn,
    dma1_6: handler_fn,
    dma1_7: handler_fn,
    adc1_2: handler_fn,
    usb_hp_can_tx: handler_fn,
    usb_lp_can_rx0: handler_fn,
    can1_rx1: handler_fn,
    can1_sce: handler_fn,
    exti9_5: handler_fn,
    tim1_brk: handler_fn,
    tim1_up: handler_fn,
    tim1_trg_con: handler_fn,
    tim1_cc: handler_fn,
    tim2: handler_fn,
    tim3: handler_fn,
    tim4: handler_fn,
    i2c1_ev: handler_fn,
    i2c1_er: handler_fn,
    i2c2_ev: handler_fn,
    i2c2_er: handler_fn,
    sp11: handler_fn,
    spi2: handler_fn,
    usart1: handler_fn,
    usart2: handler_fn,
    usart3: handler_fn,
    exti15_10: handler_fn,
    rtcalarm: handler_fn,
    usb_wkup: handler_fn,
    tim8_brk: handler_fn,
    tim8_up: handler_fn,
    tim8_trg_com: handler_fn,
    tim8_cc: handler_fn,
    adc3: handler_fn,
    fsmc: handler_fn,
    sdio: handler_fn,
    tim5: handler_fn,
    spi3: handler_fn,
    uart4: handler_fn,
    uart5: handler_fn,
    tim6: handler_fn,
    tim7: handler_fn,
    dma2_1: handler_fn,
    dma2_2: handler_fn,
    dma2_3: handler_fn,
    dma2_4_5: handler_fn,
};

export const vector_table linksection(".vectors") = vectors_other{
    .stack = _stack,
    .reset = _start,
    .nmi = null_handler,
    .hardfault = null_handler,
    .memManage = null_handler,
    .busFault = null_handler,
    .usageFault = null_handler,
    .svCall = null_handler,
    .debugMonitor = null_handler,
    .pensv = null_handler,
    .systick = null_handler,
    .wwdg = null_handler,
    .pvd = null_handler,
    .tamper = null_handler,
    .rtc = null_handler,
    .flash = null_handler,
    .rcc = null_handler,
    .exti0 = null_handler,
    .exti1 = null_handler,
    .exti2 = null_handler,
    .exti3 = null_handler,
    .exti4 = null_handler,
    .dma1_1 = null_handler,
    .dma1_2 = null_handler,
    .dma1_3 = null_handler,
    .dma1_4 = null_handler,
    .dma1_5 = null_handler,
    .dma1_6 = null_handler,
    .dma1_7 = null_handler,
    .adc1_2 = null_handler,
    .usb_hp_can_tx = null_handler,
    .usb_lp_can_rx0 = null_handler,
    .can1_rx1 = null_handler,
    .can1_sce = null_handler,
    .exti9_5 = null_handler,
    .tim1_brk = null_handler,
    .tim1_up = null_handler,
    .tim1_trg_con = null_handler,
    .tim1_cc = null_handler,
    .tim2 = null_handler,
    .tim3 = null_handler,
    .tim4 = null_handler,
    .i2c1_ev = null_handler,
    .i2c1_er = null_handler,
    .i2c2_ev = null_handler,
    .i2c2_er = null_handler,
    .sp11 = null_handler,
    .spi2 = null_handler,
    .usart1 = null_handler,
    .usart2 = null_handler,
    .usart3 = null_handler,
    .exti15_10 = null_handler,
    .rtcalarm = null_handler,
    .usb_wkup = null_handler,
    .tim8_brk = null_handler,
    .tim8_up = null_handler,
    .tim8_trg_com = null_handler,
    .tim8_cc = null_handler,
    .adc3 = null_handler,
    .fsmc = null_handler,
    .sdio = null_handler,
    .tim5 = null_handler,
    .spi3 = null_handler,
    .uart4 = null_handler,
    .uart5 = null_handler,
    .tim6 = null_handler,
    .tim7 = null_handler,
    .dma2_1 = null_handler,
    .dma2_2 = null_handler,
    .dma2_3 = null_handler,
    .dma2_4_5 = null_handler,
};
